// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_cities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUserCity = `-- name: CreateUserCity :one
INSERT INTO user_cities (id, user_id, city)
VALUES ($1, $2, $3)
RETURNING id, user_id, city, created_at
`

type CreateUserCityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	City   string
}

func (q *Queries) CreateUserCity(ctx context.Context, arg CreateUserCityParams) (UserCity, error) {
	row := q.db.QueryRow(ctx, createUserCity, arg.ID, arg.UserID, arg.City)
	var i UserCity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserCity = `-- name: DeleteUserCity :execrows
DELETE
FROM user_cities
WHERE id = $1
  AND user_id = $2
`

type DeleteUserCityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserCity(ctx context.Context, arg DeleteUserCityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserCity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserCities = `-- name: ListUserCities :many
SELECT id, user_id, city, created_at
FROM user_cities
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserCities(ctx context.Context, userID uuid.UUID) ([]UserCity, error) {
	rows, err := q.db.Query(ctx, listUserCities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCity{}
	for rows.Next() {
		var i UserCity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
