// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWeatherHistory = `-- name: CreateWeatherHistory :one
INSERT INTO weather_history (id, user_id, city, temperature, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, city, temperature, description, requested_at
`

type CreateWeatherHistoryParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	City        string
	Temperature float64
	Description string
}

func (q *Queries) CreateWeatherHistory(ctx context.Context, arg CreateWeatherHistoryParams) (WeatherHistory, error) {
	row := q.db.QueryRow(ctx, createWeatherHistory,
		arg.ID,
		arg.UserID,
		arg.City,
		arg.Temperature,
		arg.Description,
	)
	var i WeatherHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.City,
		&i.Temperature,
		&i.Description,
		&i.RequestedAt,
	)
	return i, err
}

const listWeatherHistory = `-- name: ListWeatherHistory :many
SELECT id, user_id, city, temperature, description, requested_at
FROM weather_history
WHERE user_id = $1 AND ($2 = '' OR city = $2)
ORDER BY requested_at DESC
LIMIT NULLIF($3, 0)
OFFSET $4
`

type ListWeatherHistoryParams struct {
	UserID uuid.UUID
	City   string
	Limit  int32
	Offset int32
}

func (q *Queries) ListWeatherHistory(ctx context.Context, arg ListWeatherHistoryParams) ([]WeatherHistory, error) {
	rows, err := q.db.Query(ctx, listWeatherHistory, arg.UserID, arg.City, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []WeatherHistory{}
	for rows.Next() {
		var i WeatherHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.City,
			&i.Temperature,
			&i.Description,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}
