// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWeatherHistory = `-- name: CreateWeatherHistory :one
INSERT INTO weather_history (id, user_id, city, temperature, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, city, temperature, description, requested_at
`

type CreateWeatherHistoryParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	City        string
	Temperature float64
	Description string
}

func (q *Queries) CreateWeatherHistory(ctx context.Context, arg CreateWeatherHistoryParams) (WeatherHistory, error) {
	row := q.db.QueryRow(ctx, createWeatherHistory,
		arg.ID,
		arg.UserID,
		arg.City,
		arg.Temperature,
		arg.Description,
	)
	var i WeatherHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.City,
		&i.Temperature,
		&i.Description,
		&i.RequestedAt,
	)
	return i, err
}
